In [1]:
import warnings
warnings.filterwarnings('ignore')
from matplotlib import font_manager,rc
f_name=font_manager.FontProperties(fname='C:/Windows/Fonts/NGULIM.ttf').get_name()
rc('font',family=f_name)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from fbprophet import Prophet

Importing plotly failed. Interactive plots will not work.

In [3]:
data=pd.read_csv("eco jeju/final_dataset.csv")

In [4]:
data.drop(['Unnamed: 0'],axis=1,inplace=True)

In [5]:
data=data.loc[:,:'visit_ratio']

In [6]:
data['year']=data['year'].astype(str)
data['month']=data['month'].astype(str)
data['date']=data['date'].astype(str)

In [7]:
data['base_date']=data['year']+"-"+data['month']+"-"+data['date']

In [8]:
data['base_date']=pd.to_datetime(data['base_date'])

In [9]:
data.drop(['year','month','date'],axis=1,inplace=True)

In [10]:
data.head()

,emd_nm,em_g,total_pop,제주_resd_ratio,제주_resd_pop,visit_ratio,base_date
0,건입동,1708250,10028,0.552623,7274.890502,49.642958,2018-01-01
1,남원읍,1239600,19740,0.704247,12143.821692,41.452047,2018-01-01
2,노형동,9357900,54958,0.769356,50660.687565,25.674217,2018-01-01
3,대륜동,1717700,13651,0.667224,11185.575639,42.502310,2018-01-01
4,대정읍,1264950,22603,0.784751,16075.181182,28.652628,2018-01-01

# total_pop 예측

In [11]:
test_df=pd.DataFrame(columns=['emd_nm','base_date','total_pop'])

In [13]:
for region in data['emd_nm'].unique():
    data_pop=data.loc[data['emd_nm']==region,['total_pop','base_date']]
    data_pop.rename(columns={'total_pop':'y','base_date':'ds'},inplace=True)
    model=Prophet(seasonality_mode ='multiplicative',daily_seasonality=True,yearly_seasonality=True,weekly_seasonality=True)
    model.fit(data_pop)
    future=model.make_future_dataframe(periods=90,freq='D')
    forecast=model.predict(future)
    forecast=forecast[['ds','yhat']]
    forecast.rename(columns={'ds':'base_date','yhat':'total_pop'},inplace=True)
    forecast['emd_nm']=region
    test_df=pd.concat([test_df,forecast])

In [14]:
test_df

    emd_nm  base_date     total_pop
0      건입동 2018-01-01  10029.958720
1      건입동 2018-01-02  10029.229301
2      건입동 2018-01-03  10028.231176
3      건입동 2018-01-04  10027.790760
4      건입동 2018-01-05  10027.075401
..     ...        ...           ...
682    한경면 2021-09-24   9397.473104
683    한경면 2021-09-25   9398.961819
684    한경면 2021-09-26   9399.251212
685    한경면 2021-09-27   9400.864338
686    한경면 2021-09-28   9401.558377

[54666 rows x 3 columns]

In [73]:
test_df.loc[test_df['base_date']=='2021-07-01']

     emd_nm  base_date      total_pop
1276    건입동 2021-07-01    9106.044568
1276    남원읍 2021-07-01   19346.792595
1277    노형동 2021-07-01   57471.057489
1276    대륜동 2021-07-01   15295.649018
1276    대정읍 2021-07-01   23546.018787
1276    대천동 2021-07-01   14055.605672
1277    도두동 2021-07-01    3404.986030
1276    동홍동 2021-07-01   24095.316079
1277    봉개동 2021-07-01    5322.999313
1277   삼도1동 2021-07-01   13654.883473
1277   삼도2동 2021-07-01    8189.259950
1277    삼양동 2021-07-01   26035.942015
1276    서홍동 2021-07-01   11065.607902
1276    성산읍 2021-07-01   16969.366382
1276    송산동 2021-07-01    4502.144426
1277    아라동 2021-07-01   39438.344808
1276    안덕면 2021-07-01   12734.737248
1273    애월읍 2021-07-01   38315.128926
1277     연동 2021-07-01   43805.391544
1276    영천동 2021-07-01    5306.131054
1276    예래동 2021-07-01    4155.080167
1277    오라동 2021-07-01   15946.104234
1277    외도동 2021-07-01   22387.774651
1276   용담1동 2021-07-01    7025.957949
1277   용담2동 2021-07-01   14767.950194
1277   이도1동 2021-07-01    7667.394567
1277   이도2동 2021-07-01   50098.902755
1272    이호동 2021-07-01    4674.723755
1276   일도1동 2021-07-01    2536.779043
1277   일도2동 2021-07-01   32914.118870
1276    정방동 2021-07-01    2238.371249
1276    중문동 2021-07-01   11866.859345
1276    중앙동 2021-07-01    3425.604047
1276    천지동 2021-07-01    3580.419412
1276    표선면 2021-07-01   12683.544449
1277    화북동 2021-07-01   24625.603475
1276    효돈동 2021-07-01    5314.455549
1277     전체 2021-07-01  697048.340878
605     조천읍 2021-07-01   25935.837046
600     구좌읍 2021-07-01   15956.457094
599     한림읍 2021-07-01   24475.592602
597     한경면 2021-07-01    9487.261488

# 제주_resd_ratio 예측

In [15]:
test_ratio=pd.DataFrame(columns=['emd_nm','base_date','제주_resd_ratio'])

In [16]:
for region in data['emd_nm'].unique():
    data_ratio=data.loc[data['emd_nm']==region,['제주_resd_ratio','base_date']]
    data_ratio.rename(columns={'제주_resd_ratio':'y','base_date':'ds'},inplace=True)
    model=Prophet()
    model.fit(data_ratio)
    future=model.make_future_dataframe(periods=90,freq='D')
    forecast=model.predict(future)
    forecast=forecast[['ds','yhat']]
    forecast.rename(columns={'ds':'base_date','yhat':'제주_resd_ratio'},inplace=True)
    forecast['emd_nm']=region
    test_ratio=pd.concat([test_ratio,forecast])

INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

In [17]:
test_ratio

    emd_nm  base_date  제주_resd_ratio
0      건입동 2018-01-01       0.561409
1      건입동 2018-01-02       0.554586
2      건입동 2018-01-03       0.554662
3      건입동 2018-01-04       0.555361
4      건입동 2018-01-05       0.550883
..     ...        ...            ...
682    한경면 2021-09-24       0.721874
683    한경면 2021-09-25       0.705604
684    한경면 2021-09-26       0.709587
685    한경면 2021-09-27       0.732148
686    한경면 2021-09-28       0.728364

[54666 rows x 3 columns]

# 제주_resd_pop 예측

In [18]:
test_resd_pop=pd.DataFrame(columns=['emd_nm','base_date','제주_resd_pop'])

In [19]:
for region in data['emd_nm'].unique():
    data_resd_pop=data.loc[data['emd_nm']==region,['제주_resd_pop','base_date']]
    data_resd_pop.rename(columns={'제주_resd_pop':'y','base_date':'ds'},inplace=True)
    model=Prophet()
    model.fit(data_resd_pop)
    future=model.make_future_dataframe(periods=90,freq='D')
    forecast=model.predict(future)
    forecast=forecast[['ds','yhat']]
    forecast.rename(columns={'ds':'base_date','yhat':'제주_resd_pop'},inplace=True)
    forecast['emd_nm']=region
    test_resd_pop=pd.concat([test_resd_pop,forecast])

INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

In [20]:
test_resd_pop

    emd_nm  base_date  제주_resd_pop
0      건입동 2018-01-01  7023.652037
1      건입동 2018-01-02  6965.057711
2      건입동 2018-01-03  6983.107603
3      건입동 2018-01-04  6987.668660
4      건입동 2018-01-05  6897.856300
..     ...        ...          ...
682    한경면 2021-09-24  7036.160836
683    한경면 2021-09-25  7100.241715
684    한경면 2021-09-26  7275.353278
685    한경면 2021-09-27  7077.963557
686    한경면 2021-09-28  7047.635261

[54666 rows x 3 columns]

In [62]:
merge=pd.merge(test_df,test_ratio)

In [63]:
merge=pd.merge(merge,test_resd_pop)

In [64]:
merge

      emd_nm  base_date     total_pop  제주_resd_ratio  제주_resd_pop
0        건입동 2018-01-01  10029.958720       0.561409  7023.652037
1        건입동 2018-01-02  10029.229301       0.554586  6965.057711
2        건입동 2018-01-03  10028.231176       0.554662  6983.107603
3        건입동 2018-01-04  10027.790760       0.555361  6987.668660
4        건입동 2018-01-05  10027.075401       0.550883  6897.856300
...      ...        ...           ...            ...          ...
54661    한경면 2021-09-24   9397.473104       0.721874  7036.160836
54662    한경면 2021-09-25   9398.961819       0.705604  7100.241715
54663    한경면 2021-09-26   9399.251212       0.709587  7275.353278
54664    한경면 2021-09-27   9400.864338       0.732148  7077.963557
54665    한경면 2021-09-28   9401.558377       0.728364  7047.635261

[54666 rows x 5 columns]

In [65]:
merge=merge.sort_values(by=['base_date'])

In [66]:
merge=merge.loc[(merge['base_date']>='2021-07-01')&(merge['base_date']<='2021-08-31')]

In [67]:
merge=merge.sort_values(by=['base_date','emd_nm'])

In [68]:
merge

      emd_nm  base_date     total_pop  제주_resd_ratio   제주_resd_pop
1276     건입동 2021-07-01   9106.044568       0.546794   6721.705127
53200    구좌읍 2021-07-01  15956.457094       0.744055  13501.923490
2642     남원읍 2021-07-01  19346.792595       0.771138  14556.895855
4009     노형동 2021-07-01  57471.057489       0.733652  53775.986296
5375     대륜동 2021-07-01  15295.649018       0.714609  14125.330274
...      ...        ...           ...            ...           ...
47776    표선면 2021-08-31  12674.734846       0.792154  10599.763562
54637    한경면 2021-08-31   9384.476531       0.733958   7097.621164
53950    한림읍 2021-08-31  24565.759700       0.752209  20322.779888
49143    화북동 2021-08-31  24573.282197       0.731218  25715.742872
50509    효돈동 2021-08-31   5300.963969       0.777274   4117.135468

[2604 rows x 5 columns]

In [85]:
merge.to_csv("test_data.csv")

In [86]:
test=pd.read_csv("test_data.csv")

In [87]:
test

      Unnamed: 0 emd_nm   base_date     total_pop  제주_resd_ratio   제주_resd_pop
0           1276    건입동  2021-07-01   9106.044568       0.546794   6721.705127
1          53200    구좌읍  2021-07-01  15956.457094       0.744055  13501.923490
2           2642    남원읍  2021-07-01  19346.792595       0.771138  14556.895855
3           4009    노형동  2021-07-01  57471.057489       0.733652  53775.986296
4           5375    대륜동  2021-07-01  15295.649018       0.714609  14125.330274
...          ...    ...         ...           ...            ...           ...
2599       47776    표선면  2021-08-31  12674.734846       0.792154  10599.763562
2600       54637    한경면  2021-08-31   9384.476531       0.733958   7097.621164
2601       53950    한림읍  2021-08-31  24565.759700       0.752209  20322.779888
2602       49143    화북동  2021-08-31  24573.282197       0.731218  25715.742872
2603       50509    효돈동  2021-08-31   5300.963969       0.777274   4117.135468

[2604 rows x 6 columns]

In [88]:
sh=pd.read_csv("eco jeju/test_sh.csv")

In [89]:
sh=sh[['base_date','emd_nm','visit_ratio','frgn_ratio','youth_ratio']]

In [90]:
sh

       base_date emd_nm  visit_ratio  frgn_ratio  youth_ratio
0     2021-07-01    건입동    51.067891    0.024671     0.203817
1     2021-07-01    구좌읍    41.984776    0.028941     0.211370
2     2021-07-01    남원읍    34.535098    0.027330     0.165633
3     2021-07-01    노형동    29.007228    0.032431     0.209259
4     2021-07-01    대륜동    37.638054    0.016286     0.216148
...          ...    ...          ...         ...          ...
2599  2021-08-31    표선면    45.857278    0.016488     0.178092
2600  2021-08-31    한경면    28.122740    0.091732     0.180985
2601  2021-08-31    한림읍    19.995049    0.042356     0.207132
2602  2021-08-31    화북동    32.939901    0.012226     0.167878
2603  2021-08-31    효돈동    36.023307    0.016256     0.169922

[2604 rows x 5 columns]

In [98]:
total_merge=pd.merge(sh,test,left_on=['base_date','emd_nm'],right_on=['base_date','emd_nm'])

In [99]:
total_merge.drop(['Unnamed: 0'],axis=1,inplace=True)

In [104]:
total_merge

,base_date,emd_nm,visit_ratio,frgn_ratio,youth_ratio,total_pop,제주_resd_ratio,제주_resd_pop
0,2021-07-01,건입동,51.067891,0.024671,0.203817,9106.044568,0.546794,6721.705127
1,2021-07-01,구좌읍,41.984776,0.028941,0.211370,15956.457094,0.744055,13501.923490
2,2021-07-01,남원읍,34.535098,0.027330,0.165633,19346.792595,0.771138,14556.895855
3,2021-07-01,노형동,29.007228,0.032431,0.209259,57471.057489,0.733652,53775.986296
4,2021-07-01,대륜동,37.638054,0.016286,0.216148,15295.649018,0.714609,14125.330274
...,...,...,...,...,...,...,...,...
2599,2021-08-31,표선면,45.857278,0.016488,0.178092,12674.734846,0.792154,10599.763562
2600,2021-08-31,한경면,28.122740,0.091732,0.180985,9384.476531,0.733958,7097.621164
2601,2021-08-31,한림읍,19.995049,0.042356,0.207132,24565.759700,0.752209,20322.779888
2602,2021-08-31,화북동,32.939901,0.012226,0.167878,24573.282197,0.731218,25715.742872
2603,2021-08-31,효돈동,36.023307,0.016256,0.169922,5300.963969,0.777274,4117.135468

In [105]:
total_merge.to_csv("final_testdata.csv")

In [106]:
total_merge

,base_date,emd_nm,visit_ratio,frgn_ratio,youth_ratio,total_pop,제주_resd_ratio,제주_resd_pop
0,2021-07-01,건입동,51.067891,0.024671,0.203817,9106.044568,0.546794,6721.705127
1,2021-07-01,구좌읍,41.984776,0.028941,0.211370,15956.457094,0.744055,13501.923490
2,2021-07-01,남원읍,34.535098,0.027330,0.165633,19346.792595,0.771138,14556.895855
3,2021-07-01,노형동,29.007228,0.032431,0.209259,57471.057489,0.733652,53775.986296
4,2021-07-01,대륜동,37.638054,0.016286,0.216148,15295.649018,0.714609,14125.330274
...,...,...,...,...,...,...,...,...
2599,2021-08-31,표선면,45.857278,0.016488,0.178092,12674.734846,0.792154,10599.763562
2600,2021-08-31,한경면,28.122740,0.091732,0.180985,9384.476531,0.733958,7097.621164
2601,2021-08-31,한림읍,19.995049,0.042356,0.207132,24565.759700,0.752209,20322.779888
2602,2021-08-31,화북동,32.939901,0.012226,0.167878,24573.282197,0.731218,25715.742872
2603,2021-08-31,효돈동,36.023307,0.016256,0.169922,5300.963969,0.777274,4117.135468